; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; MASTER ARDUINO
[env:Motor_Arduino]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = z3t0/IRremote@^4.7.1
build_src_filter = +<motor_control/> -<valve_control/>

; SLAVE ARDUINO
[env:Valve_Arduino]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<valve_control/> -<motor_control/>
lib_deps = z3t0/IRremote@^4.7.1
